version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=macaceres2
      - DATABASE_PASSWORD=hJkpukibu534
      - DATABASE_NAME=stock_market
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=stocks/info
    restart: always

  api2:
  build: .
  ports:
    - "8001:8000"
  environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=macaceres2
      - DATABASE_PASSWORD=hJkpukibu534
      - DATABASE_NAME=stock_market
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=stocks/info
  restart: always

  mqtt-client:
    build: .
    command: python -m app.mqtt_standalone
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=macaceres2
      - DATABASE_PASSWORD=hJkpukibu534
      - DATABASE_NAME=stock_market
      - MQTT_BROKER=broker.hivemq.com
      - MQTT_PORT=1883
      - MQTT_TOPIC=stocks/info
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=macaceres2
      - POSTGRES_PASSWORD=hJkpukibu534
      - POSTGRES_DB=stock_market
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data: